import express, { Request, Response, NextFunction } from "express";
import crypto from "node:crypto";
import { config } from "../config";
import { ModerationCase } from "../database/models/ModerationCase";
import { UserNote } from "../database/models/UserNote";
import { Client } from "discord.js";
import { LOG_EVENTS, LOG_EVENT_LABELS } from "../logging/discordLogger";
import { GuildSettings } from "../database/models/GuildSettings";

type DiscordGuild = { id: string; name: string; permissions: string; owner?: boolean };
type Session = { userId: string; username: string; guilds: DiscordGuild[]; expiresAt: number };
const sessions = new Map<string, Session>();
const ADMIN = 0x8n;

function cookieValue(req: Request, name: string): string | null {
  const header = req.headers.cookie ?? "";
  const match = header.split(";").map(v => v.trim()).find(v => v.startsWith(`${name}=`));
  return match ? decodeURIComponent(match.slice(name.length + 1)) : null;
}

async function discordToken(code: string): Promise<any> {
  const body = new URLSearchParams({ client_id: config.discord.clientId, client_secret: config.dashboard.clientSecret, grant_type: "authorization_code", code, redirect_uri: `${config.dashboard.publicUrl.replace(/\/$/, "")}/oauth/callback` });
  const response = await fetch("https://discord.com/api/v10/oauth2/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body });
  if (!response.ok) throw new Error("Discord OAuth token exchange failed.");
  return response.json();
}

async function discordGet<T>(path: string, token: string): Promise<T> {
  const response = await fetch(`https://discord.com/api/v10${path}`, { headers: { Authorization: `Bearer ${token}` } });
  if (!response.ok) throw new Error(`Discord API request failed: ${response.status}`);
  return response.json() as Promise<T>;
}

function session(req: Request): Session | null {
  const id = cookieValue(req, "cerberus_session");
  if (!id) return null;
  const value = sessions.get(id);
  if (!value || value.expiresAt < Date.now()) { sessions.delete(id); return null; }
  return value;
}

function requireSession(req: Request, res: Response, next: NextFunction): void {
  if (!session(req)) { res.status(401).json({ error: "Not authenticated." }); return; }
  next();
}

function isAdmin(s: Session, guildId: string, client: Client): boolean {
  if (!client.guilds.cache.has(guildId)) return false;
  const guild = s.guilds.find(g => g.id === guildId);
  if (!guild) return false;
  return guild.owner === true || (BigInt(guild.permissions) & ADMIN) === ADMIN;
}

function requireGuildAdmin(req: Request, res: Response, next: NextFunction): void {
  const s = session(req);
  const guildId = String(req.params.guildId);
  if (!s || !isAdmin(s, guildId, dashboardClient)) { res.status(403).json({ error: "Administrator access required." }); return; }
  next();
}

const landingPage = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#160a16"><title>Cerberus • Discord Moderation</title><style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#160a16;color:#f7f8ff}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 15% 10%,#4a102f 0,transparent 34%),radial-gradient(circle at 85% 20%,#4c1d4f 0,transparent 30%),#160a16;min-height:100vh}
a{text-decoration:none;color:inherit}.nav{height:76px;display:flex;align-items:center;justify-content:space-between;padding:0 6%;border-bottom:1px solid rgba(148,163,184,.12);background:rgba(8,11,24,.72);backdrop-filter:blur(18px);position:sticky;top:0;z-index:5}.brand{display:flex;align-items:center;gap:11px;font-size:21px;font-weight:850;letter-spacing:-.4px}.logo{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(135deg,#8f315c,#7c3f8c);box-shadow:0 10px 30px rgba(99,102,241,.3);font-size:20px}.login{padding:11px 18px;border-radius:10px;background:#fff;color:#111827;font-weight:750;box-shadow:0 8px 24px rgba(0,0,0,.2);transition:.2s}.login:hover{transform:translateY(-1px);box-shadow:0 12px 30px rgba(0,0,0,.3)}
.hero{max-width:1160px;margin:0 auto;padding:100px 6% 78px;text-align:center}.eyebrow{display:inline-flex;align-items:center;gap:8px;padding:7px 12px;border:1px solid rgba(129,140,248,.25);background:rgba(99,102,241,.1);border-radius:999px;color:#e9b8d0;font-size:13px;font-weight:700}.dot{width:7px;height:7px;border-radius:50%;background:#b14d78;box-shadow:0 0 14px #b14d78}.hero h1{font-size:clamp(42px,7vw,76px);line-height:1.02;letter-spacing:-3px;margin:22px 0 18px;background:linear-gradient(110deg,#fff 20%,#e9b8d0 55%,#b77ac7 90%);-webkit-background-clip:text;background-clip:text;color:transparent}.hero p{max-width:700px;margin:0 auto;color:#aab3c8;font-size:19px;line-height:1.7}.cta{display:flex;justify-content:center;gap:12px;margin-top:34px;flex-wrap:wrap}.cta a{padding:13px 21px;border-radius:11px;font-weight:750}.primary{background:linear-gradient(135deg,#8f315c,#7c3f8c);box-shadow:0 12px 35px rgba(99,102,241,.3)}.secondary{border:1px solid rgba(148,163,184,.22);background:rgba(15,23,42,.55);color:#dbe4f5}.trust{margin-top:34px;color:#69758c;font-size:13px}.features{max-width:1160px;margin:0 auto;padding:15px 6% 100px}.section-head{text-align:center;margin-bottom:28px}.section-head h2{font-size:30px;margin:0 0 9px}.section-head p{margin:0;color:#7f8ba3}.feature-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.feature{padding:24px;border:1px solid rgba(148,163,184,.13);background:linear-gradient(145deg,rgba(20,28,51,.82),rgba(12,16,31,.78));border-radius:17px;box-shadow:0 15px 50px rgba(0,0,0,.14)}.icon{width:44px;height:44px;border-radius:12px;display:grid;place-items:center;background:rgba(99,102,241,.14);color:#a5b4fc;font-size:20px;margin-bottom:18px}.feature h3{margin:0 0 8px;font-size:17px}.feature p{margin:0;color:#8793aa;line-height:1.65;font-size:14px}.bottom{max-width:1160px;margin:0 auto;padding:0 6% 70px}.banner{border:1px solid rgba(129,140,248,.2);border-radius:20px;padding:30px;background:linear-gradient(120deg,rgba(49,46,129,.32),rgba(30,41,59,.25));display:flex;align-items:center;justify-content:space-between;gap:20px}.banner h2{margin:0 0 7px}.banner p{margin:0;color:#929db2}.banner .login{background:#b14d78;color:#fff}@media(max-width:800px){.feature-grid{grid-template-columns:1fr}.hero{padding-top:72px}.banner{flex-direction:column;align-items:flex-start}.nav{padding:0 5%}}</style></head><body>
<header class="nav"><a class="brand" href="/"><span class="logo">🐺</span>Cerberus</a><a class="login" href="/login">Admin Login</a></header>
<section class="hero"><div class="eyebrow"><span class="dot"></span> Discord moderation, built for your staff</div><h1>Keep your community<br>under control.</h1><p>Cerberus gives Discord staff powerful moderation commands, persistent case history, private staff notes, and a clean admin dashboard — all in one place.</p><div class="cta"><a class="primary" href="/login">Open Admin Dashboard</a><a class="secondary" href="#features">Explore Features</a></div><div class="trust">Secure Discord OAuth2 • Multiguild support • Persistent SQL storage</div></section>
<section class="features" id="features"><div class="section-head"><h2>Everything your moderators need</h2><p>Simple tools for day-to-day moderation, with the history to back them up.</p></div><div class="feature-grid"><article class="feature"><div class="icon">🛡️</div><h3>Powerful Moderation</h3><p>Ban, kick, timeout, warn, purge, unban and unwarn users directly from Discord slash commands.</p></article><article class="feature"><div class="icon">📋</div><h3>Persistent Case Logs</h3><p>Every moderation action is stored with the server, user, moderator, reason and timestamp for reliable history.</p></article><article class="feature"><div class="icon">📝</div><h3>Private Staff Notes</h3><p>Keep internal notes on users so your staff can share context without exposing it to the community.</p></article><article class="feature"><div class="icon">📊</div><h3>Admin Dashboard</h3><p>Review moderation cases and staff notes from a focused web dashboard designed for server administrators.</p></article><article class="feature"><div class="icon">🏢</div><h3>Multiguild Ready</h3><p>Manage every server where Cerberus is installed while keeping each server's moderation data isolated.</p></article><article class="feature"><div class="icon">🔐</div><h3>Admin-Only Access</h3><p>Sign in through Discord OAuth2. Dashboard access is restricted to administrators of servers where Cerberus is present.</p></article></div></section>
<section class="bottom"><div class="banner"><div><h2>Ready to manage your servers?</h2><p>Sign in with Discord to access the Cerberus admin dashboard.</p></div><a class="login" href="/login">Admin Login →</a></div></section>
</body></html>`;

const sharedStyle = `<style>:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;background:#120a12;color:#f7eef5}*{box-sizing:border-box}body{margin:0;background:#120a12}header{height:64px;border-bottom:1px solid #352031;display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:#180d17;position:sticky;top:0;z-index:10}.brand{font-weight:800;font-size:20px}.muted{color:#a995a8}.navlinks{display:flex;align-items:center;gap:8px;margin-left:20px;flex:1}.navlinks a{padding:9px 13px;border-radius:8px;color:#bdaebe}.navlinks a:hover,.navlinks a.active{background:#2b1729;color:#fff}.header-left{display:flex;align-items:center;gap:16px}.panel{background:#1b101a;border:1px solid #352031;border-radius:12px;padding:18px}.guild{padding:12px;border-radius:8px;cursor:pointer;margin:4px 0}.guild:hover,.guild.active{background:#2b1729}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:18px}input,button,select{background:#150c14;color:#f7eef5;border:1px solid #443044;border-radius:8px;padding:10px}select{width:100%}button{cursor:pointer}button:hover{background:#301a2e}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:18px}.card strong{font-size:26px;display:block;margin-top:6px}.row{border-top:1px solid #352031;padding:12px 0}.badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#39233a;font-size:12px;margin-right:6px}.note{white-space:pre-wrap}.empty{padding:30px;text-align:center;color:#a995a8}.page{max-width:1280px;margin:auto;padding:28px}.page-title{margin-bottom:20px}.page-title h1{margin:0 0 6px}.page-title p{margin:0;color:#a995a8}.log-grid{display:grid;grid-template-columns:280px 1fr;gap:20px}.event-row{display:grid;grid-template-columns:1fr 280px;gap:16px;align-items:center;padding:12px 0;border-top:1px solid #352031}.save-row{display:flex;align-items:center;gap:12px;margin-top:20px}@media(max-width:850px){.cards{grid-template-columns:1fr}.log-grid{grid-template-columns:1fr}.event-row{grid-template-columns:1fr}.navlinks{margin-left:0}.header-left{gap:8px}.navlinks a{padding:8px 9px}}@media(max-width:600px){header{padding:0 14px}.brand .muted{display:none}.navlinks{overflow:auto}.navlinks a{white-space:nowrap}}</style>`;

function dashboardHeader(active: "moderation" | "logging" | "notes"): string {
  return `<header><div class="header-left"><a class="brand" href="/dashboard">🐺 Cerberus <span class="muted">Admin Dashboard</span></a><nav class="navlinks"><a class="${active === "moderation" ? "active" : ""}" href="/dashboard">Moderation</a><a class="${active === "logging" ? "active" : ""}" href="/dashboard/logging">Event Logging</a><a class="${active === "notes" ? "active" : ""}" href="/dashboard/notes">Notes</a></nav></div><button onclick="logout()">Logout</button></header>`;
}

function dashboardScript(): string {
  return `<script>const state={guild:null};const esc=function(s){return String(s||'').replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})};async function api(path){const r=await fetch(path);if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.error||'Request failed')}return r.json()}async function getGuilds(){const d=await api('/api/guilds');if(!d.guilds.length)throw new Error('No Discord servers where you have Administrator access were found.');if(!state.guild)state.guild=d.guilds[0].id;return d.guilds}function guildSidebar(guilds){return '<aside class="panel"><h3>Servers</h3>'+guilds.map(function(g){return '<div class="guild '+(g.id===state.guild?'active':'')+'" onclick="selectGuild(\\''+g.id+'\\')">'+esc(g.name)+'</div>'}).join('')+'</aside>'}function selectGuild(id){state.guild=id;loadPage()}async function logout(){await fetch('/logout',{method:'POST'});location.href='/'};</script>`;
}

function moderationPage(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cerberus • Moderation</title>${sharedStyle}</head><body>${dashboardHeader("moderation")}<main class="page"><div class="page-title"><h1>Moderation</h1><p>Review moderation cases for each server.</p></div><div id="app" class="empty">Loading...</div></main>${dashboardScript()}<script>async function loadLogs(){if(!state.guild)return;const el=document.getElementById('userId');const user=el?el.value.trim():'';try{const d=await api('/api/guild/'+state.guild+'/logs'+(user?'?userId='+encodeURIComponent(user):''));document.getElementById('stats').innerHTML='<div class="cards"><div class="panel card"><span class="muted">Moderation cases</span><strong>'+d.cases.length+'</strong></div><div class="panel card"><span class="muted">Viewing</span><strong>'+esc(user||'All users')+'</strong></div></div>';let html='<h3>Moderation Cases</h3>';html+=d.cases.length?d.cases.map(function(c){return '<div class="row"><span class="badge">Case #'+c.id+'</span><span class="badge">'+esc(c.action)+'</span><b>User:</b> '+esc(c.userId)+' <span class="muted">by '+esc(c.moderatorId)+' • '+new Date(c.createdAt).toLocaleString()+'</span><div>'+esc(c.reason)+'</div><div style="margin-top:10px;display:flex;gap:8px"><button onclick="editCase('+c.id+',\\''+esc(c.action)+'\\',\\''+String(c.reason||'').replace(/\\\\/g,'').replace(/\\'/g,'')+'\\')">Edit</button><button onclick="deleteCase('+c.id+')">Delete</button></div></div>'}).join(''):'<div class="empty">No moderation cases.</div>';document.getElementById('logs').innerHTML=html}catch(e){document.getElementById('logs').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}async function editCase(id,action,currentReason){const nextReason=prompt('Edit moderation reason:',currentReason);if(nextReason===null)return;const nextAction=prompt('Edit action (BAN, UNBAN, KICK, TIMEOUT, WARN, PURGE, UNWARN):',action);if(nextAction===null)return;const r=await fetch('/api/guild/'+state.guild+'/moderation/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:nextReason,action:nextAction.trim().toUpperCase()})});if(!r.ok){const d=await r.json();alert(d.error||'Failed to update case.');return}await loadLogs()}
async function deleteCase(id){if(!confirm('Delete this moderation case from the database?'))return;const r=await fetch('/api/guild/'+state.guild+'/moderation/'+id,{method:'DELETE'});if(!r.ok){const d=await r.json();alert(d.error||'Failed to delete case.');return}await loadLogs()}
async function loadPage(){try{const guilds=await getGuilds();document.getElementById('app').innerHTML='<div class="log-grid"><aside class="panel"><h3>Servers</h3>'+guilds.map(function(g){return '<div class="guild '+(g.id===state.guild?'active':'')+'" onclick="selectGuild(\\''+g.id+'\\')">'+esc(g.name)+'</div>'}).join('')+'</aside><section><div class="panel"><div class="toolbar"><input id="userId" placeholder="Filter by Discord User ID"><button onclick="loadLogs()">Search</button><button onclick="document.getElementById(\\'userId\\').value=\\'\\';loadLogs()">All users</button></div><div id="stats"></div></div><div class="panel"><div id="logs"></div></div></section></div>';await loadLogs()}catch(e){document.getElementById('app').innerHTML='<div class="panel">'+esc(e.message)+'</div>'}}loadPage();</script></body></html>`;
}

function loggingPage(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cerberus • Event Logging</title>${sharedStyle}</head><body>${dashboardHeader("logging")}<main class="page"><div class="page-title"><h1>Event Logging</h1><p>Configure where Cerberus sends Discord event logs. Moderation records remain on the Moderation page.</p></div><div id="app" class="empty">Loading...</div></main>${dashboardScript()}<script>async function loadLogConfig(){try{const guilds=await getGuilds();document.getElementById('app').innerHTML='<div class="log-grid">'+guildSidebar(guilds)+'<section class="panel"><h2>Logging Channels</h2><p class="muted">Choose a channel for each event type. Leave an event disabled to stop logging it.</p><div id="logConfig">Loading logging settings...</div></section></div>';await renderLogConfig()}catch(e){document.getElementById('app').innerHTML='<div class="panel">'+esc(e.message)+'</div>'}}async function renderLogConfig(){const box=document.getElementById('logConfig');try{const data=await api('/api/guild/'+state.guild+'/log-config');const channels=await api('/api/guild/'+state.guild+'/channels');const options='<option value="">Disabled</option>'+channels.channels.map(function(ch){return '<option value="'+ch.id+'">#'+esc(ch.name)+'</option>'}).join('');box.innerHTML=data.events.map(function(ev){return '<div class="event-row"><label>'+esc(ev.label)+'</label><select data-log-event="'+ev.key+'">'+options+'</select></div>'}).join('')+'<div class="save-row"><button onclick="saveLogConfig()">Save Logging Configuration</button><span id="logSave" class="muted"></span></div>';data.events.forEach(function(ev){const s=document.querySelector('[data-log-event="'+ev.key+'"]');if(s)s.value=(data.channels||{})[ev.key]||''})}catch(e){box.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}async function saveLogConfig(){const channels={};document.querySelectorAll('[data-log-event]').forEach(function(s){channels[s.dataset.logEvent]=s.value});const out=document.getElementById('logSave');try{const r=await fetch('/api/guild/'+state.guild+'/log-config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({channels})});if(!r.ok){const d=await r.json();throw new Error(d.error||'Failed to save')}out.textContent='Saved';setTimeout(function(){out.textContent=''},2000)}catch(e){out.textContent=e.message}}function loadPage(){loadLogConfig()}loadPage();</script></body></html>`;
}

function notesPage(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cerberus • Staff Notes</title>${sharedStyle}</head><body>${dashboardHeader("notes")}<main class="page"><div class="page-title"><h1>Staff Notes</h1><p>Manage private staff notes separately from moderation cases and event logging.</p></div><div id="app" class="empty">Loading...</div></main>${dashboardScript()}<script>
async function loadPage(){try{const guilds=await getGuilds();document.getElementById('app').innerHTML='<div class="log-grid"><aside class="panel"><h3>Servers</h3>'+guilds.map(function(g){return '<div class="guild '+(g.id===state.guild?'active':'')+'" onclick="selectGuild(\\''+g.id+'\\')">'+esc(g.name)+'</div>'}).join('')+'</aside><section><div class="panel"><div class="toolbar"><input id="userId" placeholder="Filter by Discord User ID"><button onclick="loadNotes()">Search</button><button onclick="clearFilter()">All users</button></div><div id="noteStats"></div></div><div class="panel"><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><input id="newUserId" placeholder="Discord User ID"><input id="newNote" placeholder="Private staff note"><button onclick="addNote()" style="grid-column:1/-1">Add Staff Note</button></div></div><div class="panel"><div id="notes"></div></div></section></div>';await loadNotes()}catch(e){document.getElementById('app').innerHTML='<div class="panel">'+esc(e.message)+'</div>'}}
function clearFilter(){document.getElementById('userId').value='';loadNotes()}
async function loadNotes(){const user=document.getElementById('userId')?.value.trim()||'';try{const d=await api('/api/guild/'+state.guild+'/notes'+(user?'?userId='+encodeURIComponent(user):''));document.getElementById('noteStats').innerHTML='<div class="cards"><div class="panel card"><span class="muted">Notes</span><strong>'+d.notes.length+'</strong></div><div class="panel card"><span class="muted">Viewing</span><strong>'+esc(user||'All users')+'</strong></div><div class="panel card"><span class="muted">Server</span><strong>'+esc(state.guild)+'</strong></div></div>';document.getElementById('notes').innerHTML=d.notes.length?d.notes.map(function(n){return '<div class="row"><span class="badge">Note #'+n.id+'</span><b>User:</b> '+esc(n.userId)+' <span class="muted">by '+esc(n.authorId)+' • '+new Date(n.createdAt).toLocaleString()+'</span><div class="note">'+esc(n.note)+'</div><div style="margin-top:10px;display:flex;gap:8px"><button onclick="editNote('+n.id+',\\''+String(n.note||'').replace(/\\\\/g,'').replace(/\\'/g,'')+'\\')">Edit</button><button onclick="deleteNote('+n.id+')">Delete</button></div></div>'}).join(''):'<div class="empty">No staff notes.</div>'}catch(e){document.getElementById('notes').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function addNote(){const userId=document.getElementById('newUserId').value.trim(),note=document.getElementById('newNote').value.trim();if(!/^\\d{15,25}$/.test(userId)||!note){alert('Enter a valid Discord User ID and note.');return}const r=await fetch('/api/guild/'+state.guild+'/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,note})});if(!r.ok){const d=await r.json();alert(d.error||'Failed to add note.');return}document.getElementById('newNote').value='';await loadNotes()}
async function editNote(id,currentNote){const next=prompt('Edit staff note:',currentNote);if(next===null||!next.trim())return;const r=await fetch('/api/guild/'+state.guild+'/notes/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:next})});if(!r.ok){const d=await r.json();alert(d.error||'Failed to update note.');return}await loadNotes()}
async function deleteNote(id){if(!confirm('Delete this staff note from the database?'))return;const r=await fetch('/api/guild/'+state.guild+'/notes/'+id,{method:'DELETE'});if(!r.ok){const d=await r.json();alert(d.error||'Failed to delete note.');return}await loadNotes()}
loadPage();</script></body></html>`;
}

let dashboardClient: Client;

export function startDashboard(client: Client): void {
  dashboardClient = client;
  if (!config.dashboard.enabled) return;
  if (!config.dashboard.clientSecret || config.dashboard.clientSecret === "CHANGE_ME") { console.warn("Dashboard disabled: set dashboard.clientSecret in config.js."); return; }
  const app = express();
  app.use(express.json());
  app.get("/", (req,res) => { if (!session(req)) { res.type("html").send(landingPage); return; } res.redirect("/dashboard"); });
  app.get("/dashboard", (req,res) => { if (!session(req)) return res.redirect("/login"); res.type("html").send(moderationPage()); });
  app.get("/dashboard/logging", (req,res) => { if (!session(req)) return res.redirect("/login"); res.type("html").send(loggingPage()); });
  app.get("/dashboard/notes", (req,res) => { if (!session(req)) return res.redirect("/login"); res.type("html").send(notesPage()); });
  app.get("/login", (_req,res) => { const state=crypto.randomBytes(24).toString("hex"); const redirect=`${config.dashboard.publicUrl.replace(/\/$/,"")}/oauth/callback`; const url=new URL("https://discord.com/oauth2/authorize"); url.searchParams.set("client_id",config.discord.clientId); url.searchParams.set("response_type","code"); url.searchParams.set("redirect_uri",redirect); url.searchParams.set("scope","identify guilds"); url.searchParams.set("state",state); res.setHeader("Set-Cookie",`cerberus_oauth_state=${state}; HttpOnly; Secure; SameSite=Lax; Path=/`); res.redirect(url.toString()); });
  app.get("/oauth/callback", async (req,res) => { try { const code=String(req.query.code??""); const expected=cookieValue(req,"cerberus_oauth_state"); if(!code||!expected||expected!==String(req.query.state??"")) return res.status(400).send("Invalid OAuth state."); const token=await discordToken(code); const user=await discordGet<{id:string;username:string}>("/users/@me",token.access_token); const guilds=await discordGet<DiscordGuild[]>("/users/@me/guilds",token.access_token); const sid=crypto.randomBytes(32).toString("hex"); sessions.set(sid,{userId:user.id,username:user.username,guilds:guilds.filter(g=>g.owner||(BigInt(g.permissions)&ADMIN)===ADMIN),expiresAt:Date.now()+8*60*60*1000}); res.setHeader("Set-Cookie",`cerberus_session=${sid}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=28800`); res.redirect("/dashboard"); } catch(e) { res.status(500).send("Discord login failed."); } });
  app.post("/logout",(req,res)=>{const id=cookieValue(req,"cerberus_session");if(id)sessions.delete(id);res.setHeader("Set-Cookie","cerberus_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0");res.status(204).end();});
  app.get("/api/guilds",requireSession,(req,res)=>{const s=session(req)!;res.json({guilds:s.guilds.filter(g=>client.guilds.cache.has(g.id))})});
  app.get("/api/guild/:guildId/channels",requireGuildAdmin,async(req,res)=>{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const channels=[...guild.channels.cache.values()].filter(c=>c.isTextBased() && "send" in c).map(c=>({id:c.id,name:c.name,type:c.type}));res.json({channels});});
  app.get("/api/guild/:guildId/log-config",requireGuildAdmin,async(req,res)=>{const [settings]=await GuildSettings.findOrCreate({where:{guildId:String(req.params.guildId)}});res.json({channels:settings.eventLogChannels??{},events:LOG_EVENTS.map(event=>({key:event,label:LOG_EVENT_LABELS[event]}))});});
  app.put("/api/guild/:guildId/log-config",requireGuildAdmin,async(req,res)=>{try{const guild=client.guilds.cache.get(req.params.guildId);if(!guild)return res.status(404).json({error:"Server not found."});const incoming=(req.body?.channels??{}) as Record<string,unknown>;const channels:any={};for(const event of LOG_EVENTS){const value=incoming[event];if(value==null||value===""){channels[event]=null;continue;}const channel=guild.channels.cache.get(String(value));if(!channel||!channel.isTextBased()||!("send" in channel))return res.status(400).json({error:"Invalid channel for "+LOG_EVENT_LABELS[event]+"."});channels[event]=channel.id;}const [settings]=await GuildSettings.findOrCreate({where:{guildId:guild.id}});settings.eventLogChannels=channels;if(channels.moderation)settings.modLogChannelId=channels.moderation;await settings.save();res.json({ok:true,channels});}catch(e){res.status(500).json({error:"Failed to save logging configuration."});}});
  app.put("/api/guild/:guildId/moderation/:caseId",requireGuildAdmin,async(req,res)=>{try{const c=await ModerationCase.findOne({where:{id:Number(req.params.caseId),guildId:String(req.params.guildId)}});if(!c)return res.status(404).json({error:"Moderation case not found."});if(typeof req.body?.reason==="string"&&req.body.reason.trim())c.reason=req.body.reason.trim().slice(0,500);if(typeof req.body?.action==="string"&&["BAN","UNBAN","KICK","TIMEOUT","WARN","PURGE","UNWARN"].includes(req.body.action))c.action=req.body.action;await c.save();res.json({ok:true,case:c});}catch(e){res.status(500).json({error:"Failed to update moderation case."})}});
  app.delete("/api/guild/:guildId/moderation/:caseId",requireGuildAdmin,async(req,res)=>{try{const c=await ModerationCase.findOne({where:{id:Number(req.params.caseId),guildId:req.params.guildId}});if(!c)return res.status(404).json({error:"Moderation case not found."});await c.destroy();res.json({ok:true});}catch(e){res.status(500).json({error:"Failed to delete moderation case."})}});
  app.get("/api/guild/:guildId/notes",requireGuildAdmin,async(req,res)=>{try{const where:any={guildId:req.params.guildId};if(req.query.userId)where.userId=String(req.query.userId);const notes=await UserNote.findAll({where,order:[["createdAt","DESC"]],limit:100});res.json({notes});}catch(e){res.status(500).json({error:"Database query failed."})}});
  app.post("/api/guild/:guildId/notes",requireGuildAdmin,async(req,res)=>{try{const userId=String(req.body?.userId??"").trim();const note=String(req.body?.note??"").trim();if(!/^\\d{15,25}$/.test(userId))return res.status(400).json({error:"Invalid Discord user ID. Discord user IDs are numeric snowflake IDs."});if(!note)return res.status(400).json({error:"Note cannot be empty."});if(note.length>2000)return res.status(400).json({error:"Note must be 2000 characters or fewer."});const row=await UserNote.create({guildId:req.params.guildId,userId,authorId:session(req)!.userId,note});res.json({ok:true,note:row});}catch(e){res.status(500).json({error:"Failed to create staff note."})}});
  app.put("/api/guild/:guildId/notes/:noteId",requireGuildAdmin,async(req,res)=>{try{const row=await UserNote.findOne({where:{id:Number(req.params.noteId),guildId:req.params.guildId}});if(!row)return res.status(404).json({error:"Staff note not found."});const note=String(req.body?.note??"").trim();if(!note)return res.status(400).json({error:"Note cannot be empty."});if(note.length>2000)return res.status(400).json({error:"Note must be 2000 characters or fewer."});row.note=note;await row.save();res.json({ok:true,note:row});}catch(e){res.status(500).json({error:"Failed to update staff note."})}});
  app.delete("/api/guild/:guildId/notes/:noteId",requireGuildAdmin,async(req,res)=>{try{const row=await UserNote.findOne({where:{id:Number(req.params.noteId),guildId:req.params.guildId}});if(!row)return res.status(404).json({error:"Staff note not found."});await row.destroy();res.json({ok:true});}catch(e){res.status(500).json({error:"Failed to delete staff note."})}});
  app.get("/api/guild/:guildId/logs",requireGuildAdmin,async(req,res)=>{try{const where:any={guildId:req.params.guildId};if(req.query.userId)where.userId=String(req.query.userId);const cases=await ModerationCase.findAll({where,order:[["createdAt","DESC"]],limit:100});res.json({cases});}catch(e){res.status(500).json({error:"Database query failed."})}});
  app.listen(config.dashboard.port,()=>console.log(`Cerberus dashboard listening on port ${config.dashboard.port}`));
}