import express, { Request, Response, NextFunction } from "express";
import crypto from "node:crypto";
import { config } from "../config";
import { ModerationCase } from "../database/models/ModerationCase";
import { UserNote } from "../database/models/UserNote";
import { Client } from "discord.js";
import { LOG_EVENTS, LOG_EVENT_LABELS } from "../logging/discordLogger";
import { GuildSettings } from "../database/models/GuildSettings";
import { TicketSettings } from "../database/models/TicketSettings";
import { TicketPanel } from "../database/models/TicketPanel";
import { TicketTranscript } from "../database/models/TicketTranscript";
import { publishTicketPanel } from "../commands/tickets";
import { sendGlobalAnnouncement } from "../commands/developer";
import { VerificationSettings } from "../database/models/VerificationSettings";
import { VerificationPanel } from "../database/models/VerificationPanel";
import { publishVerificationPanel } from "../commands/verification";

type DiscordGuild = { id: string; name: string; permissions: string; owner?: boolean };
type Session = { userId: string; username: string; guilds: DiscordGuild[]; expiresAt: number };
const sessions = new Map<string, Session>();
const ADMIN = 0x8n;

function cookieValue(req: Request, name: string): string | null {
  const header = req.headers.cookie ?? "";
  const match = header.split(";").map(v => v.trim()).find(v => v.startsWith(`${name}=`));
  return match ? decodeURIComponent(match.slice(name.length + 1)) : null;
}

async function discordToken(code: string): Promise<any> {
  const body = new URLSearchParams({ client_id: config.discord.clientId, client_secret: config.dashboard.clientSecret, grant_type: "authorization_code", code, redirect_uri: `${config.dashboard.publicUrl.replace(/\/$/, "")}/oauth/callback` });
  const response = await fetch("https://discord.com/api/v10/oauth2/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body });
  if (!response.ok) throw new Error("Discord OAuth token exchange failed.");
  return response.json();
}

async function discordGet<T>(path: string, token: string): Promise<T> {
  const response = await fetch(`https://discord.com/api/v10${path}`, { headers: { Authorization: `Bearer ${token}` } });
  if (!response.ok) throw new Error(`Discord API request failed: ${response.status}`);
  return response.json() as Promise<T>;
}

function session(req: Request): Session | null {
  const id = cookieValue(req, "cerberus_session");
  if (!id) return null;
  const value = sessions.get(id);
  if (!value || value.expiresAt < Date.now()) { sessions.delete(id); return null; }
  return value;
}

function requireSession(req: Request, res: Response, next: NextFunction): void {
  if (!session(req)) { res.status(401).json({ error: "Not authenticated." }); return; }
  next();
}

function isGlobalAdmin(userId: string): boolean {
  return (config.dashboard.globalAdmins ?? []).includes(userId);
}

function isAdmin(s: Session, guildId: string, client: Client): boolean {
  if (!client.guilds.cache.has(guildId)) return false;
  if (isGlobalAdmin(s.userId)) return true;
  const guild = s.guilds.find(g => g.id === guildId);
  if (!guild) return false;
  return guild.owner === true || (BigInt(guild.permissions) & ADMIN) === ADMIN;
}

function requireGlobalAdmin(req: Request, res: Response, next: NextFunction): void {
  const s=session(req);
  if(!s||!isGlobalAdmin(s.userId)){res.status(403).json({error:"Global administrator access required."});return;}
  next();
}

function requireGuildAdmin(req: Request, res: Response, next: NextFunction): void {
  const s = session(req);
  const guildId = String(req.params.guildId);
  if (!s || !isAdmin(s, guildId, dashboardClient)) { res.status(403).json({ error: "Administrator access required." }); return; }
  next();
}

const landingPage = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#160a16"><title>Cerberus • Discord Moderation</title><style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#160a16;color:#f7f8ff}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 15% 10%,#4a102f 0,transparent 34%),radial-gradient(circle at 85% 20%,#4c1d4f 0,transparent 30%),#160a16;min-height:100vh}
a{text-decoration:none;color:inherit}.nav{height:76px;display:flex;align-items:center;justify-content:space-between;padding:0 6%;border-bottom:1px solid rgba(148,163,184,.12);background:rgba(8,11,24,.72);backdrop-filter:blur(18px);position:sticky;top:0;z-index:5}.brand{display:flex;align-items:center;gap:11px;font-size:21px;font-weight:850;letter-spacing:-.4px}.logo{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(135deg,#8f315c,#7c3f8c);box-shadow:0 10px 30px rgba(99,102,241,.3);font-size:20px}.login{padding:11px 18px;border-radius:10px;background:#fff;color:#111827;font-weight:750;box-shadow:0 8px 24px rgba(0,0,0,.2);transition:.2s}.login:hover{transform:translateY(-1px);box-shadow:0 12px 30px rgba(0,0,0,.3)}
.hero{max-width:1160px;margin:0 auto;padding:100px 6% 78px;text-align:center}.eyebrow{display:inline-flex;align-items:center;gap:8px;padding:7px 12px;border:1px solid rgba(129,140,248,.25);background:rgba(99,102,241,.1);border-radius:999px;color:#e9b8d0;font-size:13px;font-weight:700}.dot{width:7px;height:7px;border-radius:50%;background:#b14d78;box-shadow:0 0 14px #b14d78}.hero h1{font-size:clamp(42px,7vw,76px);line-height:1.02;letter-spacing:-3px;margin:22px 0 18px;background:linear-gradient(110deg,#fff 20%,#e9b8d0 55%,#b77ac7 90%);-webkit-background-clip:text;background-clip:text;color:transparent}.hero p{max-width:700px;margin:0 auto;color:#aab3c8;font-size:19px;line-height:1.7}.cta{display:flex;justify-content:center;gap:12px;margin-top:34px;flex-wrap:wrap}.cta a{padding:13px 21px;border-radius:11px;font-weight:750}.primary{background:linear-gradient(135deg,#8f315c,#7c3f8c);box-shadow:0 12px 35px rgba(99,102,241,.3)}.secondary{border:1px solid rgba(148,163,184,.22);background:rgba(15,23,42,.55);color:#dbe4f5}.trust{margin-top:34px;color:#69758c;font-size:13px}.features{max-width:1160px;margin:0 auto;padding:15px 6% 100px}.section-head{text-align:center;margin-bottom:28px}.section-head h2{font-size:30px;margin:0 0 9px}.section-head p{margin:0;color:#7f8ba3}.feature-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.feature{padding:24px;border:1px solid rgba(148,163,184,.13);background:linear-gradient(145deg,rgba(20,28,51,.82),rgba(12,16,31,.78));border-radius:17px;box-shadow:0 15px 50px rgba(0,0,0,.14)}.icon{width:44px;height:44px;border-radius:12px;display:grid;place-items:center;background:rgba(99,102,241,.14);color:#a5b4fc;font-size:20px;margin-bottom:18px}.feature h3{margin:0 0 8px;font-size:17px}.feature p{margin:0;color:#8793aa;line-height:1.65;font-size:14px}.bottom{max-width:1160px;margin:0 auto;padding:0 6% 70px}.banner{border:1px solid rgba(129,140,248,.2);border-radius:20px;padding:30px;background:linear-gradient(120deg,rgba(49,46,129,.32),rgba(30,41,59,.25));display:flex;align-items:center;justify-content:space-between;gap:20px}.banner h2{margin:0 0 7px}.banner p{margin:0;color:#929db2}.banner .login{background:#b14d78;color:#fff}@media(max-width:800px){.feature-grid{grid-template-columns:1fr}.hero{padding-top:72px}.banner{flex-direction:column;align-items:flex-start}.nav{padding:0 5%}}</style></head><body>
<header class="nav"><a class="brand" href="/"><span class="logo">🐺</span>Cerberus</a><a class="login" href="/login">Admin Login</a></header>
<section class="hero"><div class="eyebrow"><span class="dot"></span> Discord moderation, built for your staff</div><h1>Keep your community<br>under control.</h1><p>Cerberus gives Discord staff powerful moderation commands, persistent case history, private staff notes, and a clean admin dashboard — all in one place.</p><div class="cta"><a class="primary" href="/login">Open Admin Dashboard</a><a class="secondary" href="#features">Explore Features</a></div><div class="trust">Secure Discord OAuth2 • Multiguild support • Persistent SQL storage</div></section>
<section class="features" id="features"><div class="section-head"><h2>Everything your moderators need</h2><p>Simple tools for day-to-day moderation, with the history to back them up.</p></div><div class="feature-grid"><article class="feature"><div class="icon">🛡️</div><h3>Powerful Moderation</h3><p>Ban, kick, timeout, warn, purge, unban and unwarn users directly from Discord slash commands.</p></article><article class="feature"><div class="icon">📋</div><h3>Persistent Case Logs</h3><p>Every moderation action is stored with the server, user, moderator, reason and timestamp for reliable history.</p></article><article class="feature"><div class="icon">📝</div><h3>Private Staff Notes</h3><p>Keep internal notes on users so your staff can share context without exposing it to the community.</p></article><article class="feature"><div class="icon">📊</div><h3>Admin Dashboard</h3><p>Review moderation cases and staff notes from a focused web dashboard designed for server administrators.</p></article><article class="feature"><div class="icon">🏢</div><h3>Multiguild Ready</h3><p>Manage every server where Cerberus is installed while keeping each server's moderation data isolated.</p></article><article class="feature"><div class="icon">🔐</div><h3>Admin-Only Access</h3><p>Sign in through Discord OAuth2. Dashboard access is restricted to administrators of servers where Cerberus is present.</p></article></div></section>
<section class="bottom"><div class="banner"><div><h2>Ready to manage your servers?</h2><p>Sign in with Discord to access the Cerberus admin dashboard.</p></div><a class="login" href="/login">Admin Login →</a></div></section>
</body></html>`;

const sharedStyle = `<style>:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;background:#120a12;color:#f7eef5}*{box-sizing:border-box}body{margin:0;background:#120a12}header{height:64px;border-bottom:1px solid #352031;display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:#180d17;position:sticky;top:0;z-index:10}.brand{font-weight:800;font-size:20px}.muted{color:#a995a8}.navlinks{display:flex;align-items:center;gap:8px;margin-left:20px;flex:1}.navlinks a{padding:9px 13px;border-radius:8px;color:#bdaebe}.navlinks a:hover,.navlinks a.active{background:#2b1729;color:#fff}.header-left{display:flex;align-items:center;gap:16px}.panel{background:#1b101a;border:1px solid #352031;border-radius:12px;padding:18px}.guild{padding:12px;border-radius:8px;cursor:pointer;margin:4px 0}.guild:hover,.guild.active{background:#2b1729}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:18px}input,button,select{background:#150c14;color:#f7eef5;border:1px solid #443044;border-radius:8px;padding:10px}select{width:100%}button{cursor:pointer}button:hover{background:#301a2e}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:18px}.card strong{font-size:26px;display:block;margin-top:6px}.row{border-top:1px solid #352031;padding:12px 0}.badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#39233a;font-size:12px;margin-right:6px}.note{white-space:pre-wrap}.empty{padding:30px;text-align:center;color:#a995a8}.page{max-width:1280px;margin:auto;padding:28px}.page-title{margin-bottom:20px}.page-title h1{margin:0 0 6px}.page-title p{margin:0;color:#a995a8}.log-grid{display:grid;grid-template-columns:280px 1fr;gap:20px}.event-row{display:grid;grid-template-columns:1fr 280px;gap:16px;align-items:center;padding:12px 0;border-top:1px solid #352031}.save-row{display:flex;align-items:center;gap:12px;margin-top:20px}@media(max-width:850px){.cards{grid-template-columns:1fr}.log-grid{grid-template-columns:1fr}.event-row{grid-template-columns:1fr}.navlinks{margin-left:0}.header-left{gap:8px}.navlinks a{padding:8px 9px}}@media(max-width:600px){header{padding:0 14px}.brand .muted{display:none}.navlinks{overflow:auto}.navlinks a{white-space:nowrap}}</style>`;

function dashboardHeader(active: "moderation" | "logging" | "notes" | "tickets" | "transcripts" | "verification" | "developer", globalAdmin=false): string {
  return `<header><div class="header-left"><a class="brand" href="/dashboard">🐺 Cerberus <span class="muted">Admin Dashboard</span></a><nav class="navlinks"><a class="${active === "moderation" ? "active" : ""}" href="/dashboard">Moderation</a><a class="${active === "logging" ? "active" : ""}" href="/dashboard/logging">Event Logging</a><a class="${active === "notes" ? "active" : ""}" href="/dashboard/notes">Notes</a><a class="${active === "tickets" ? "active" : ""}" href="/dashboard/tickets">Tickets</a><a class="${active === "transcripts" ? "active" : ""}" href="/dashboard/transcripts">Transcripts</a><a class="${active === "verification" ? "active" : ""}" href="/dashboard/verification">Verification</a>${globalAdmin ? `<a class="${active === "developer" ? "active" : ""}" href="/dashboard/developer">Developer</a>` : ""}</nav></div><button onclick="logout()">Logout</button></header>`;
}

function dashboardScript(): string {
  return `<script>const state={guild:null};const esc=function(s){return String(s||'').replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})};async function api(path){const r=await fetch(path);if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.error||'Request failed')}return r.json()}async function getGuilds(){const d=await api('/api/guilds');if(d.globalAdmin&&!document.querySelector('.navlinks a[href="/dashboard/developer"]')){const n=document.querySelector('.navlinks');if(n)n.insertAdjacentHTML('beforeend','<a href="/dashboard/developer">Developer</a>')};if(!d.guilds.length)throw new Error('No Discord servers where you have Administrator access were found.');if(!state.guild)state.guild=d.guilds[0].id;return d.guilds}function guildSidebar(guilds){return '<aside class="panel"><h3>Servers</h3>'+guilds.map(function(g){return '<div class="guild '+(g.id===state.guild?'active':'')+'" onclick="selectGuild(\\''+g.id+'\\')">'+esc(g.name)+'</div>'}).join('')+'</aside>'}function selectGuild(id){state.guild=id;loadPage()}async function logout(){await fetch('/logout',{method:'POST'});location.href='/'};</script>`;
}

function moderationPage(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cerberus • Moderation</title>${sharedStyle}</head><body>${dashboardHeader("moderation")}<main class="page"><div class="page-title"><h1>Moderation</h1><p>Review moderation cases for each server.</p></div><div id="app" class="empty">Loading...</div></main>${dashboardScript()}<script>async function loadLogs(){if(!state.guild)return;const el=document.getElementById('userId');const user=el?el.value.trim():'';try{const d=await api('/api/guild/'+state.guild+'/logs'+(user?'?userId='+encodeURIComponent(user):''));document.getElementById('stats').innerHTML='<div class="cards"><div class="panel card"><span class="muted">Moderation cases</span><strong>'+d.cases.length+'</strong></div><div class="panel card"><span class="muted">Viewing</span><strong>'+esc(user||'All users')+'</strong></div></div>';let html='<h3>Moderation Cases</h3>';html+=d.cases.length?d.cases.map(function(c){return '<div class="row"><span class="badge">Case #'+c.id+'</span><span class="badge">'+esc(c.action)+'</span><b>User:</b> '+esc(c.userId)+' <span class="muted">by '+esc(c.moderatorId)+' • '+new Date(c.createdAt).toLocaleString()+'</span><div>'+esc(c.reason)+'</div><div style="margin-top:10px;display:flex;gap:8px"><button onclick="editCase('+c.id+',\\''+esc(c.action)+'\\',\\''+String(c.reason||'').replace(/\\\\/g,'').replace(/\\'/g,'')+'\\')">Edit</button><button onclick="deleteCase('+c.id+')">Delete</button></div></div>'}).join(''):'<div class="empty">No moderation cases.</div>';document.getElementById('logs').innerHTML=html}catch(e){document.getElementById('logs').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}async function editCase(id,action,currentReason){const nextReason=prompt('Edit moderation reason:',currentReason);if(nextReason===null)return;const nextAction=prompt('Edit action (BAN, UNBAN, KICK, TIMEOUT, WARN, PURGE, UNWARN):',action);if(nextAction===null)return;const r=await fetch('/api/guild/'+state.guild+'/moderation/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:nextReason,action:nextAction.trim().toUpperCase()})});if(!r.ok){const d=await r.json();alert(d.error||'Failed to update case.');return}await loadLogs()}
async function deleteCase(id){if(!confirm('Delete this moderation case from the database?'))return;const r=await fetch('/api/guild/'+state.guild+'/moderation/'+id,{method:'DELETE'});if(!r.ok){const d=await r.json();alert(d.error||'Failed to delete case.');return}await loadLogs()}
async function loadPage(){try{const guilds=await getGuilds();document.getElementById('app').innerHTML='<div class="log-grid"><aside class="panel"><h3>Servers</h3>'+guilds.map(function(g){return '<div class="guild '+(g.id===state.guild?'active':'')+'" onclick="selectGuild(\\''+g.id+'\\')">'+esc(g.name)+'</div>'}).join('')+'</aside><section><div class="panel"><div class="toolbar"><input id="userId" placeholder="Filter by Discord User ID"><button onclick="loadLogs()">Search</button><button onclick="document.getElementById(\\'userId\\').value=\\'\\';loadLogs()">All users</button></div><div id="stats"></div></div><div class="panel"><div id="logs"></div></div></section></div>';await loadLogs()}catch(e){document.getElementById('app').innerHTML='<div class="panel">'+esc(e.message)+'</div>'}}loadPage();</script></body></html>`;
}

function loggingPage(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cerberus • Event Logging</title>${sharedStyle}</head><body>${dashboardHeader("logging")}<main class="page"><div class="page-title"><h1>Event Logging</h1><p>Configure where Cerberus sends Discord event logs. Moderation records remain on the Moderation page.</p></div><div id="app" class="empty">Loading...</div></main>${dashboardScript()}<script>async function loadLogConfig(){try{const guilds=await getGuilds();document.getElementById('app').innerHTML='<div class="log-grid">'+guildSidebar(guilds)+'<section class="panel"><h2>Logging Channels</h2><p class="muted">Choose a channel for each event type. Leave an event disabled to stop logging it.</p><div id="logConfig">Loading logging settings...</div></section></div>';await renderLogConfig()}catch(e){document.getElementById('app').innerHTML='<div class="panel">'+esc(e.message)+'</div>'}}async function renderLogConfig(){const box=document.getElementById('logConfig');try{const data=await api('/api/guild/'+state.guild+'/log-config');const channels=await api('/api/guild/'+state.guild+'/channels');const options='<option value="">Disabled</option>'+channels.channels.map(function(ch){return '<option value="'+ch.id+'">#'+esc(ch.name)+'</option>'}).join('');box.innerHTML=data.events.map(function(ev){return '<div class="event-row"><label>'+esc(ev.label)+'</label><select data-log-event="'+ev.key+'">'+options+'</select></div>'}).join('')+'<div class="save-row"><button onclick="saveLogConfig()">Save Logging Configuration</button><span id="logSave" class="muted"></span></div>';data.events.forEach(function(ev){const s=document.querySelector('[data-log-event="'+ev.key+'"]');if(s)s.value=(data.channels||{})[ev.key]||''})}catch(e){box.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}async function saveLogConfig(){const channels={};document.querySelectorAll('[data-log-event]').forEach(function(s){channels[s.dataset.logEvent]=s.value});const out=document.getElementById('logSave');try{const r=await fetch('/api/guild/'+state.guild+'/log-config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({channels})});if(!r.ok){const d=await r.json();throw new Error(d.error||'Failed to save')}out.textContent='Saved';setTimeout(function(){out.textContent=''},2000)}catch(e){out.textContent=e.message}}function loadPage(){loadLogConfig()}loadPage();</script></body></html>`;
}

function notesPage(): string {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cerberus • Staff Notes</title>${sharedStyle}</head><body>${dashboardHeader("notes")}<main class="page"><div class="page-title"><h1>Staff Notes</h1><p>Manage private staff notes separately from moderation cases and event logging.</p></div><div id="app" class="empty">Loading...</div></main>${dashboardScript()}<script>
async function loadPage(){try{const guilds=await getGuilds();document.getElementById('app').innerHTML='<div class="log-grid"><aside class="panel"><h3>Servers</h3>'+guilds.map(function(g){return '<div class="guild '+(g.id===state.guild?'active':'')+'" onclick="selectGuild(\\''+g.id+'\\')">'+esc(g.name)+'</div>'}).join('')+'</aside><section><div class="panel"><div class="toolbar"><input id="userId" placeholder="Filter by Discord User ID"><button onclick="loadNotes()">Search</button><button onclick="clearFilter()">All users</button></div><div id="noteStats"></div></div><div class="panel"><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><input id="newUserId" placeholder="Discord User ID"><input id="newNote" placeholder="Private staff note"><button onclick="addNote()" style="grid-column:1/-1">Add Staff Note</button></div></div><div class="panel"><div id="notes"></div></div></section></div>';await loadNotes()}catch(e){document.getElementById('app').innerHTML='<div class="panel">'+esc(e.message)+'</div>'}}
function clearFilter(){document.getElementById('userId').value='';loadNotes()}
async function loadNotes(){const user=document.getElementById('userId')?.value.trim()||'';try{const d=await api('/api/guild/'+state.guild+'/notes'+(user?'?userId='+encodeURIComponent(user):''));document.getElementById('noteStats').innerHTML='<div class="cards"><div class="panel card"><span class="muted">Notes</span><strong>'+d.notes.length+'</strong></div><div class="panel card"><span class="muted">Viewing</span><strong>'+esc(user||'All users')+'</strong></div><div class="panel card"><span class="muted">Server</span><strong>'+esc(state.guild)+'</strong></div></div>';document.getElementById('notes').innerHTML=d.notes.length?d.notes.map(function(n){return '<div class="row"><span class="badge">Note #'+n.id+'</span><b>User:</b> '+esc(n.userId)+' <span class="muted">by '+esc(n.authorId)+' • '+new Date(n.createdAt).toLocaleString()+'</span><div class="note">'+esc(n.note)+'</div><div style="margin-top:10px;display:flex;gap:8px"><button onclick="editNote('+n.id+',\\''+String(n.note||'').replace(/\\\\/g,'').replace(/\\'/g,'')+'\\')">Edit</button><button onclick="deleteNote('+n.id+')">Delete</button></div></div>'}).join(''):'<div class="empty">No staff notes.</div>'}catch(e){document.getElementById('notes').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function addNote(){const userId=document.getElementById('newUserId').value.trim(),note=document.getElementById('newNote').value.trim();if(!/^\\d{15,25}$/.test(userId)||!note){alert('Enter a valid Discord User ID and note.');return}const r=await fetch('/api/guild/'+state.guild+'/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,note})});if(!r.ok){const d=await r.json();alert(d.error||'Failed to add note.');return}document.getElementById('newNote').value='';await loadNotes()}
async function editNote(id,currentNote){const next=prompt('Edit staff note:',currentNote);if(next===null||!next.trim())return;const r=await fetch('/api/guild/'+state.guild+'/notes/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:next})});if(!r.ok){const d=await r.json();alert(d.error||'Failed to update note.');return}await loadNotes()}
async function deleteNote(id){if(!confirm('Delete this staff note from the database?'))return;const r=await fetch('/api/guild/'+state.guild+'/notes/'+id,{method:'DELETE'});if(!r.ok){const d=await r.json();alert(d.error||'Failed to delete note.');return}await loadNotes()}
loadPage();</script></body></html>`;
}

function ticketsPage(): string {
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cerberus • Tickets</title>${sharedStyle}</head><body>${dashboardHeader("tickets")}<main class="page"><div class="page-title"><h1>Ticket System</h1><p>Configure ticket channels, staff access, logging, and publish ticket panels.</p></div><div id="app" class="empty">Loading...</div></main>${dashboardScript()}<script>
async function loadPage(){try{const guilds=await getGuilds();document.getElementById('app').innerHTML='<div class="log-grid">'+guildSidebar(guilds)+'<section><div class="panel"><h2>Ticket Configuration</h2><div id="ticketConfig">Loading...</div></div><div class="panel" style="margin-top:18px"><h2>Create Ticket Panel</h2><div id="panelForm">Loading...</div></div><div class="panel" style="margin-top:18px"><h2>Existing Panels</h2><div id="panels">Loading...</div></div></section></div>';await renderTickets()}catch(e){document.getElementById('app').innerHTML='<div class="panel">'+esc(e.message)+'</div>'}}
async function renderTickets(){const data=await api('/api/guild/'+state.guild+'/ticket-config');const opts=function(items,selected,empty){return '<option value="">'+empty+'</option>'+items.map(function(x){return '<option value="'+x.id+'" '+(x.id===selected?'selected':'')+'>'+esc(x.name)+'</option>'}).join('')};document.getElementById('ticketConfig').innerHTML='<div class="event-row"><label>Ticket Category</label><select id="ticketCategory">'+opts(data.categories,data.settings.categoryId,'Select category')+'</select></div><div class="event-row"><label>Ticket Log Channel</label><select id="ticketLogs">'+opts(data.channels,data.settings.logChannelId,'Select log channel')+'</select></div><div class="event-row"><label>Staff Role</label><select id="ticketStaff">'+opts(data.roles,data.settings.staffRoleId,'Select staff role')+'</select></div><div class="save-row"><button onclick="saveTicketConfig()">Save Ticket Configuration</button><span id="ticketSave" class="muted"></span></div>';document.getElementById('panelForm').innerHTML='<div style="display:grid;gap:10px"><input id="panelName" placeholder="Panel name"><input id="panelTitle" placeholder="Panel embed title"><input id="panelDescription" placeholder="Panel description"><input id="panelButton" placeholder="Button label (Open Ticket)"><select id="panelChannel">'+opts(data.channels,'','Publish in channel')+'</select><button onclick="createPanel()">Create & Publish Panel</button></div>';document.getElementById('panels').innerHTML=data.panels.length?data.panels.map(function(p){return '<div class="row"><b>'+esc(p.name)+'</b><div>'+esc(p.title)+'</div><span class="muted">'+(p.channelId?'Published in <#'+esc(p.channelId)+'>':'Not published')+'</span><div style="margin-top:10px"><button onclick="deletePanel('+p.id+')">Delete Panel</button></div></div>'}).join(''):'<div class="empty">No ticket panels yet.</div>'}
async function saveTicketConfig(){const body={categoryId:document.getElementById('ticketCategory').value,logChannelId:document.getElementById('ticketLogs').value,staffRoleId:document.getElementById('ticketStaff').value};const r=await fetch('/api/guild/'+state.guild+'/ticket-config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();document.getElementById('ticketSave').textContent=r.ok?'Saved':(d.error||'Failed');}
async function createPanel(){const body={name:document.getElementById('panelName').value.trim(),title:document.getElementById('panelTitle').value.trim(),description:document.getElementById('panelDescription').value.trim(),buttonLabel:document.getElementById('panelButton').value.trim()||'Open Ticket',channelId:document.getElementById('panelChannel').value};const r=await fetch('/api/guild/'+state.guild+'/ticket-panels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){alert(d.error||'Failed to create panel');return}await renderTickets()}
async function deletePanel(id){if(!confirm('Delete this ticket panel? This will also delete its Discord message if it still exists.'))return;const r=await fetch('/api/guild/'+state.guild+'/ticket-panels/'+id,{method:'DELETE'});const d=await r.json();if(!r.ok){alert(d.error||'Failed to delete panel');return}await renderTickets()}
loadPage();</script></body></html>`;
}

function verificationPage(): string {
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cerberus • Verification</title>${sharedStyle}</head><body>${dashboardHeader("verification")}<main class="page"><div class="page-title"><h1>Verification</h1><p>Configure the verified role and publish verification panels.</p></div><div id="app" class="empty">Loading...</div></main>${dashboardScript()}<script>
async function loadPage(){try{const guilds=await getGuilds();document.getElementById('app').innerHTML='<div class="log-grid">'+guildSidebar(guilds)+'<section><div id="verification"></div></section></div>';await renderVerification()}catch(e){document.getElementById('app').innerHTML='<div class="panel">'+esc(e.message)+'</div>'}}
async function renderVerification(){const d=await api('/api/guild/'+state.guild+'/verification-config');const roleOptions='<option value="">Select verified role</option>'+d.roles.map(r=>'<option value="'+r.id+'">'+esc(r.name)+'</option>').join('');const channelOptions='<option value="">Select publish channel</option>'+d.channels.map(ch=>'<option value="'+ch.id+'">'+esc(ch.name)+'</option>').join('');document.getElementById('verification').innerHTML='<div class="panel"><h2>Verification Configuration</h2><p class="muted">Members who click a verification button receive this role.</p><label>Verified Role</label><select id="verifiedRole">'+roleOptions+'</select><div class="save-row"><button onclick="saveVerification()">Save Configuration</button><span id="verifySave" class="muted"></span></div></div><div class="panel" style="margin-top:18px"><h2>Create Verification Panel</h2><input id="verifyPanelName" placeholder="Panel name" style="width:100%;margin-bottom:10px"><input id="verifyTitle" placeholder="Embed title" style="width:100%;margin-bottom:10px"><textarea id="verifyDescription" placeholder="Verification instructions" rows="5" style="width:100%;margin-bottom:10px;background:#150c14;color:#f7eef5;border:1px solid #443044;border-radius:8px;padding:10px"></textarea><input id="verifyButton" placeholder="Button label (Verify)" style="width:100%;margin-bottom:10px"><select id="verifyChannel">'+channelOptions+'</select><div class="save-row"><button onclick="createVerificationPanel()">Publish Panel</button></div><h3>Existing Panels</h3><div id="verificationPanels">'+(d.panels.length?d.panels.map(p=>'<div class="row"><b>'+esc(p.name)+'</b><div class="muted">'+esc(p.title)+'</div><button style="margin-top:8px" onclick="deleteVerificationPanel('+p.id+')">Delete Panel</button></div>').join(''):'<div class="empty">No verification panels.</div>')+'</div></div>';document.getElementById('verifiedRole').value=d.settings?.roleId||''}
async function saveVerification(){const roleId=document.getElementById('verifiedRole').value;const r=await fetch('/api/guild/'+state.guild+'/verification-config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({roleId})});const d=await r.json();document.getElementById('verifySave').textContent=r.ok?'Saved':(d.error||'Failed')}
async function createVerificationPanel(){const body={name:document.getElementById('verifyPanelName').value.trim(),title:document.getElementById('verifyTitle').value.trim(),description:document.getElementById('verifyDescription').value.trim(),buttonLabel:document.getElementById('verifyButton').value.trim()||'Verify',channelId:document.getElementById('verifyChannel').value};const r=await fetch('/api/guild/'+state.guild+'/verification-panels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){alert(d.error||'Failed to create panel');return}await renderVerification()}
async function deleteVerificationPanel(id){if(!confirm('Delete this verification panel and its Discord message?'))return;const r=await fetch('/api/guild/'+state.guild+'/verification-panels/'+id,{method:'DELETE'});const d=await r.json();if(!r.ok){alert(d.error||'Failed to delete panel');return}await renderVerification()}
loadPage();</script></body></html>`;
}

function developerPage(): string {
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cerberus • Developer Announcements</title>${sharedStyle}</head><body>${dashboardHeader("developer",true)}<main class="page"><div class="page-title"><h1>Developer Announcements</h1><p>Send maintenance, incident, and service announcements to administrators across every Cerberus server.</p></div><section class="panel" style="max-width:850px"><h2>Global Announcement</h2><p class="muted">This will DM server owners and users with Administrator permission. Administrators shared across multiple servers receive one message.</p><textarea id="announcement" maxlength="4000" rows="10" placeholder="Enter the announcement..." style="width:100%;resize:vertical;background:#150c14;color:#f7eef5;border:1px solid #443044;border-radius:8px;padding:12px"></textarea><div class="save-row"><button id="sendButton" onclick="sendAnnouncement()">Send Global Announcement</button><span id="status" class="muted"></span></div><div id="result"></div></section></main>${dashboardScript()}<script>
async function sendAnnouncement(){const message=document.getElementById('announcement').value.trim();if(!message){alert('Enter an announcement first.');return}if(!confirm('Send this announcement to administrators across every Cerberus server?'))return;const button=document.getElementById('sendButton'),status=document.getElementById('status');button.disabled=true;status.textContent='Sending...';document.getElementById('result').innerHTML='';try{const r=await fetch('/api/developer/announce',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Announcement failed');document.getElementById('result').innerHTML='<div class="cards" style="margin-top:18px"><div class="panel card"><span class="muted">Servers</span><strong>'+d.servers+'</strong></div><div class="panel card"><span class="muted">Admins found</span><strong>'+d.adminUsers+'</strong></div><div class="panel card"><span class="muted">Delivered</span><strong>'+d.delivered+'</strong></div></div><div class="muted">Failed/disabled DMs: '+d.failed+' • Server scan failures: '+d.guildFailures+'</div>';status.textContent='Announcement sent';}catch(e){status.textContent=e.message}finally{button.disabled=false}}
</script></body></html>`;
}

function transcriptsPage(): string {
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cerberus • Transcripts</title>${sharedStyle}</head><body>${dashboardHeader("transcripts")}<main class="page"><div class="page-title"><h1>Ticket Transcripts</h1><p>Review archived HTML transcripts from closed tickets.</p></div><div id="app" class="empty">Loading...</div></main>${dashboardScript()}<script>
async function loadPage(){try{const guilds=await getGuilds();document.getElementById('app').innerHTML='<div class="log-grid">'+guildSidebar(guilds)+'<section class="panel"><h2>Closed Ticket Transcripts</h2><div id="transcripts">Loading...</div></section></div>';await loadTranscripts()}catch(e){document.getElementById('app').innerHTML='<div class="panel">'+esc(e.message)+'</div>'}}
async function loadTranscripts(){const d=await api('/api/guild/'+state.guild+'/transcripts');document.getElementById('transcripts').innerHTML=d.transcripts.length?d.transcripts.map(function(t){return '<div class="row"><span class="badge">Ticket #'+t.ticketId+'</span><b>'+esc(t.channelName)+'</b><div class="muted">User '+esc(t.userId)+' • Closed by '+esc(t.closedBy)+' • '+new Date(t.createdAt).toLocaleString()+'</div><div style="margin-top:10px"><button onclick="window.open(\\'/api/guild/'+state.guild+'/transcripts/'+t.id+'\\',\\'_blank\\')">View Transcript</button></div></div>'}).join(''):'<div class="empty">No archived ticket transcripts yet.</div>'}
loadPage();</script></body></html>`;
}

let dashboardClient: Client;

export function startDashboard(client: Client): void {
  dashboardClient = client;
  if (!config.dashboard.enabled) return;
  if (!config.dashboard.clientSecret || config.dashboard.clientSecret === "CHANGE_ME") { console.warn("Dashboard disabled: set dashboard.clientSecret in config.js."); return; }
  const app = express();
  app.use(express.json());
  app.get("/", (req,res) => { if (!session(req)) { res.type("html").send(landingPage); return; } res.redirect("/dashboard"); });
  app.get("/dashboard", (req,res) => { if (!session(req)) return res.redirect("/login"); res.type("html").send(moderationPage()); });
  app.get("/dashboard/logging", (req,res) => { if (!session(req)) return res.redirect("/login"); res.type("html").send(loggingPage()); });
  app.get("/dashboard/notes", (req,res) => { if (!session(req)) return res.redirect("/login"); res.type("html").send(notesPage()); });
  app.get("/dashboard/tickets", (req,res) => { if (!session(req)) return res.redirect("/login"); res.type("html").send(ticketsPage()); });
  app.get("/dashboard/transcripts", (req,res) => { if (!session(req)) return res.redirect("/login"); res.type("html").send(transcriptsPage()); });
  app.get("/dashboard/verification", (req,res) => { if (!session(req)) return res.redirect("/login"); res.type("html").send(verificationPage()); });
  app.get("/dashboard/developer", (req,res) => { const s=session(req); if(!s)return res.redirect("/login"); if(!isGlobalAdmin(s.userId))return res.status(403).send("Global administrator access required."); res.type("html").send(developerPage()); });
  app.get("/login", (_req,res) => { const state=crypto.randomBytes(24).toString("hex"); const redirect=`${config.dashboard.publicUrl.replace(/\/$/,"")}/oauth/callback`; const url=new URL("https://discord.com/oauth2/authorize"); url.searchParams.set("client_id",config.discord.clientId); url.searchParams.set("response_type","code"); url.searchParams.set("redirect_uri",redirect); url.searchParams.set("scope","identify guilds"); url.searchParams.set("state",state); res.setHeader("Set-Cookie",`cerberus_oauth_state=${state}; HttpOnly; Secure; SameSite=Lax; Path=/`); res.redirect(url.toString()); });
  app.get("/oauth/callback", async (req,res) => { try { const code=String(req.query.code??""); const expected=cookieValue(req,"cerberus_oauth_state"); if(!code||!expected||expected!==String(req.query.state??"")) return res.status(400).send("Invalid OAuth state."); const token=await discordToken(code); const user=await discordGet<{id:string;username:string}>("/users/@me",token.access_token); const guilds=await discordGet<DiscordGuild[]>("/users/@me/guilds",token.access_token); const sid=crypto.randomBytes(32).toString("hex"); sessions.set(sid,{userId:user.id,username:user.username,guilds:guilds.filter(g=>g.owner||(BigInt(g.permissions)&ADMIN)===ADMIN),expiresAt:Date.now()+8*60*60*1000}); res.setHeader("Set-Cookie",`cerberus_session=${sid}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=28800`); res.redirect("/dashboard"); } catch(e) { res.status(500).send("Discord login failed."); } });
  app.post("/logout",(req,res)=>{const id=cookieValue(req,"cerberus_session");if(id)sessions.delete(id);res.setHeader("Set-Cookie","cerberus_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0");res.status(204).end();});
  app.post("/api/developer/announce",requireGlobalAdmin,async(req,res)=>{try{const message=String(req.body?.message??"").trim();if(!message)return res.status(400).json({error:"Announcement message is required."});if(message.length>4000)return res.status(400).json({error:"Announcement must be 4000 characters or fewer."});const result=await sendGlobalAnnouncement(client,message);res.json(result);}catch(e){console.error("Dashboard global announcement failed:",e);res.status(500).json({error:"Failed to send global announcement."})}});
  app.get("/transcripts/:token",async(req,res)=>{try{const token=String(req.params.token??"");if(!/^[a-f0-9]{64}$/.test(token))return res.status(404).send("Transcript not found.");const transcript=await TicketTranscript.findOne({where:{accessToken:token}});if(!transcript)return res.status(404).send("Transcript not found.");res.setHeader("Content-Type","text/html; charset=utf-8");res.setHeader("Content-Security-Policy","default-src 'none'; img-src https: data:; style-src 'unsafe-inline';");res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Referrer-Policy","no-referrer");res.setHeader("Cache-Control","private, no-store");res.send(transcript.html);}catch(e){res.status(500).send("Failed to load transcript.");}});
  app.get("/api/guilds",requireSession,(req,res)=>{const s=session(req)!;if(isGlobalAdmin(s.userId)){return res.json({guilds:[...client.guilds.cache.values()].map(g=>({id:g.id,name:g.name,permissions:"0",owner:false})),globalAdmin:true});}res.json({guilds:s.guilds.filter(g=>client.guilds.cache.has(g.id)),globalAdmin:false})});

  app.get("/api/guild/:guildId/verification-config",requireGuildAdmin,async(req,res)=>{try{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const [settings]=await VerificationSettings.findOrCreate({where:{guildId:guild.id}});const panels=await VerificationPanel.findAll({where:{guildId:guild.id},order:[["createdAt","DESC"]]});const channels=[...guild.channels.cache.values()].filter(ch=>ch.type===0).map(ch=>({id:ch.id,name:"#"+ch.name}));const roles=[...guild.roles.cache.values()].filter(role=>role.id!==guild.roles.everyone.id&&!role.managed).sort((a,b)=>b.position-a.position).map(role=>({id:role.id,name:role.name}));res.json({settings,panels,channels,roles});}catch(e){res.status(500).json({error:"Failed to load verification configuration."})}});
  app.put("/api/guild/:guildId/verification-config",requireGuildAdmin,async(req,res)=>{try{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const roleId=String(req.body?.roleId??"");const role=guild.roles.cache.get(roleId);if(!role||role.id===guild.roles.everyone.id||role.managed)return res.status(400).json({error:"Select a valid assignable verified role."});const me=guild.members.me;if(!me||!me.permissions.has("ManageRoles")||role.position>=me.roles.highest.position)return res.status(400).json({error:"Cerberus needs Manage Roles and its role must be above the verified role."});const [settings]=await VerificationSettings.findOrCreate({where:{guildId:guild.id}});settings.roleId=role.id;await settings.save();res.json({ok:true,settings});}catch(e){res.status(500).json({error:"Failed to save verification configuration."})}});
  app.post("/api/guild/:guildId/verification-panels",requireGuildAdmin,async(req,res)=>{try{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const settings=await VerificationSettings.findByPk(guild.id);if(!settings?.roleId)return res.status(400).json({error:"Configure a verified role first."});const name=String(req.body?.name??"").trim(),title=String(req.body?.title??"").trim(),description=String(req.body?.description??"").trim(),buttonLabel=String(req.body?.buttonLabel??"Verify").trim(),channelId=String(req.body?.channelId??"");if(!name||!title||!description||!channelId)return res.status(400).json({error:"Name, title, description and publish channel are required."});const panel=await VerificationPanel.create({guildId:guild.id,name:name.slice(0,100),title:title.slice(0,256),description:description.slice(0,2000),buttonLabel:buttonLabel.slice(0,80)||"Verify"});try{await publishVerificationPanel(guild,panel,channelId)}catch(e){await panel.destroy();return res.status(400).json({error:"Could not publish the verification panel in that channel."})}res.json({ok:true,panel});}catch(e){res.status(500).json({error:"Failed to create verification panel."})}});
  app.delete("/api/guild/:guildId/verification-panels/:panelId",requireGuildAdmin,async(req,res)=>{try{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const panel=await VerificationPanel.findOne({where:{id:Number(req.params.panelId),guildId:guild.id}});if(!panel)return res.status(404).json({error:"Verification panel not found."});if(panel.channelId&&panel.messageId){const channel=await guild.channels.fetch(panel.channelId).catch(()=>null);if(channel?.isTextBased()&&"messages" in channel){const message=await channel.messages.fetch(panel.messageId).catch(()=>null);if(message)await message.delete().catch(()=>null);}}await panel.destroy();res.json({ok:true});}catch(e){res.status(500).json({error:"Failed to delete verification panel."})}});
  app.get("/api/guild/:guildId/transcripts",requireGuildAdmin,async(req,res)=>{try{const transcripts=await TicketTranscript.findAll({where:{guildId:String(req.params.guildId)},attributes:["id","ticketId","guildId","userId","closedBy","channelName","createdAt"],order:[["createdAt","DESC"]],limit:200});res.json({transcripts});}catch(e){res.status(500).json({error:"Failed to load ticket transcripts."})}});
  app.get("/api/guild/:guildId/transcripts/:transcriptId",requireGuildAdmin,async(req,res)=>{try{const transcript=await TicketTranscript.findOne({where:{id:Number(req.params.transcriptId),guildId:String(req.params.guildId)}});if(!transcript)return res.status(404).send("Transcript not found.");res.setHeader("Content-Type","text/html; charset=utf-8");res.setHeader("Content-Security-Policy","default-src 'none'; img-src https: data:; style-src 'unsafe-inline';");res.setHeader("X-Content-Type-Options","nosniff");res.send(transcript.html);}catch(e){res.status(500).send("Failed to load transcript.");}});
  app.get("/api/guild/:guildId/ticket-config",requireGuildAdmin,async(req,res)=>{try{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const [settings]=await TicketSettings.findOrCreate({where:{guildId:guild.id}});const panels=await TicketPanel.findAll({where:{guildId:guild.id},order:[["createdAt","DESC"]]});const channels=[...guild.channels.cache.values()].filter(ch=>ch.type===0).map(ch=>({id:ch.id,name:"#"+ch.name}));const categories=[...guild.channels.cache.values()].filter(ch=>ch.type===4).map(ch=>({id:ch.id,name:ch.name}));const roles=[...guild.roles.cache.values()].filter(role=>role.id!==guild.roles.everyone.id).sort((a,b)=>b.position-a.position).map(role=>({id:role.id,name:role.name}));res.json({settings,panels,channels,categories,roles});}catch(e){res.status(500).json({error:"Failed to load ticket configuration."})}});
  app.put("/api/guild/:guildId/ticket-config",requireGuildAdmin,async(req,res)=>{try{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const categoryId=String(req.body?.categoryId??""),logChannelId=String(req.body?.logChannelId??""),staffRoleId=String(req.body?.staffRoleId??"");const category=guild.channels.cache.get(categoryId),logs=guild.channels.cache.get(logChannelId),role=guild.roles.cache.get(staffRoleId);if(!category||category.type!==4)return res.status(400).json({error:"Select a valid ticket category."});if(!logs||logs.type!==0)return res.status(400).json({error:"Select a valid ticket log channel."});if(!role)return res.status(400).json({error:"Select a valid staff role."});const [settings]=await TicketSettings.findOrCreate({where:{guildId:guild.id}});settings.categoryId=categoryId;settings.logChannelId=logChannelId;settings.staffRoleId=staffRoleId;await settings.save();res.json({ok:true,settings});}catch(e){res.status(500).json({error:"Failed to save ticket configuration."})}});
  app.post("/api/guild/:guildId/ticket-panels",requireGuildAdmin,async(req,res)=>{try{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const name=String(req.body?.name??"").trim(),title=String(req.body?.title??"").trim(),description=String(req.body?.description??"").trim(),buttonLabel=String(req.body?.buttonLabel??"Open Ticket").trim(),channelId=String(req.body?.channelId??"");if(!name||!title||!description||!channelId)return res.status(400).json({error:"Name, title, description and publish channel are required."});const panel=await TicketPanel.create({guildId:guild.id,name:name.slice(0,100),title:title.slice(0,256),description:description.slice(0,2000),buttonLabel:buttonLabel.slice(0,80)||"Open Ticket"});try{await publishTicketPanel(guild,panel,channelId)}catch(e){await panel.destroy();return res.status(400).json({error:"Could not publish the panel in that channel."})}res.json({ok:true,panel});}catch(e){res.status(500).json({error:"Failed to create ticket panel."})}});
  app.delete("/api/guild/:guildId/ticket-panels/:panelId",requireGuildAdmin,async(req,res)=>{try{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const panel=await TicketPanel.findOne({where:{id:Number(req.params.panelId),guildId:guild.id}});if(!panel)return res.status(404).json({error:"Ticket panel not found."});if(panel.channelId&&panel.messageId){const channel=await guild.channels.fetch(panel.channelId).catch(()=>null);if(channel?.isTextBased()&&"messages" in channel){const message=await channel.messages.fetch(panel.messageId).catch(()=>null);if(message)await message.delete().catch(()=>null);}}await panel.destroy();res.json({ok:true});}catch(e){res.status(500).json({error:"Failed to delete ticket panel."})}});
  app.get("/api/guild/:guildId/channels",requireGuildAdmin,async(req,res)=>{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const channels=[...guild.channels.cache.values()].filter(c=>c.isTextBased() && "send" in c).map(c=>({id:c.id,name:c.name,type:c.type}));res.json({channels});});
  app.get("/api/guild/:guildId/log-config",requireGuildAdmin,async(req,res)=>{const [settings]=await GuildSettings.findOrCreate({where:{guildId:String(req.params.guildId)}});res.json({channels:settings.eventLogChannels??{},events:LOG_EVENTS.map(event=>({key:event,label:LOG_EVENT_LABELS[event]}))});});
  app.put("/api/guild/:guildId/log-config",requireGuildAdmin,async(req,res)=>{try{const guild=client.guilds.cache.get(String(req.params.guildId));if(!guild)return res.status(404).json({error:"Server not found."});const incoming=(req.body?.channels??{}) as Record<string,unknown>;const channels:any={};for(const event of LOG_EVENTS){const value=incoming[event];if(value==null||value===""){channels[event]=null;continue;}const channel=guild.channels.cache.get(String(value));if(!channel||!channel.isTextBased()||!("send" in channel))return res.status(400).json({error:"Invalid channel for "+LOG_EVENT_LABELS[event]+"."});channels[event]=channel.id;}const [settings]=await GuildSettings.findOrCreate({where:{guildId:guild.id}});settings.eventLogChannels=channels;if(channels.moderation)settings.modLogChannelId=channels.moderation;await settings.save();res.json({ok:true,channels});}catch(e){res.status(500).json({error:"Failed to save logging configuration."});}});
  app.put("/api/guild/:guildId/moderation/:caseId",requireGuildAdmin,async(req,res)=>{try{const c=await ModerationCase.findOne({where:{id:Number(req.params.caseId),guildId:String(req.params.guildId)}});if(!c)return res.status(404).json({error:"Moderation case not found."});if(typeof req.body?.reason==="string"&&req.body.reason.trim())c.reason=req.body.reason.trim().slice(0,500);if(typeof req.body?.action==="string"&&["BAN","UNBAN","KICK","TIMEOUT","WARN","PURGE","UNWARN"].includes(req.body.action))c.action=req.body.action;await c.save();res.json({ok:true,case:c});}catch(e){res.status(500).json({error:"Failed to update moderation case."})}});
  app.delete("/api/guild/:guildId/moderation/:caseId",requireGuildAdmin,async(req,res)=>{try{const c=await ModerationCase.findOne({where:{id:Number(req.params.caseId),guildId:req.params.guildId}});if(!c)return res.status(404).json({error:"Moderation case not found."});await c.destroy();res.json({ok:true});}catch(e){res.status(500).json({error:"Failed to delete moderation case."})}});
  app.get("/api/guild/:guildId/notes",requireGuildAdmin,async(req,res)=>{try{const where:any={guildId:req.params.guildId};if(req.query.userId)where.userId=String(req.query.userId);const notes=await UserNote.findAll({where,order:[["createdAt","DESC"]],limit:100});res.json({notes});}catch(e){res.status(500).json({error:"Database query failed."})}});
  app.post("/api/guild/:guildId/notes",requireGuildAdmin,async(req,res)=>{try{const userId=String(req.body?.userId??"").trim();const note=String(req.body?.note??"").trim();const normalizedUserId=userId.replace(/^<@!?([0-9]+)>$/,"$1");if(!/^[0-9]{15,25}$/.test(normalizedUserId))return res.status(400).json({error:"Invalid Discord user ID. Enter the numeric ID, or a Discord mention such as <@123456789012345678>."});if(!note)return res.status(400).json({error:"Note cannot be empty."});if(note.length>2000)return res.status(400).json({error:"Note must be 2000 characters or fewer."});const row=await UserNote.create({guildId:String(req.params.guildId),userId:normalizedUserId,authorId:session(req)!.userId,note});res.json({ok:true,note:row});}catch(e){res.status(500).json({error:"Failed to create staff note."})}});
  app.put("/api/guild/:guildId/notes/:noteId",requireGuildAdmin,async(req,res)=>{try{const row=await UserNote.findOne({where:{id:Number(req.params.noteId),guildId:req.params.guildId}});if(!row)return res.status(404).json({error:"Staff note not found."});const note=String(req.body?.note??"").trim();if(!note)return res.status(400).json({error:"Note cannot be empty."});if(note.length>2000)return res.status(400).json({error:"Note must be 2000 characters or fewer."});row.note=note;await row.save();res.json({ok:true,note:row});}catch(e){res.status(500).json({error:"Failed to update staff note."})}});
  app.delete("/api/guild/:guildId/notes/:noteId",requireGuildAdmin,async(req,res)=>{try{const row=await UserNote.findOne({where:{id:Number(req.params.noteId),guildId:req.params.guildId}});if(!row)return res.status(404).json({error:"Staff note not found."});await row.destroy();res.json({ok:true});}catch(e){res.status(500).json({error:"Failed to delete staff note."})}});
  app.get("/api/guild/:guildId/logs",requireGuildAdmin,async(req,res)=>{try{const where:any={guildId:req.params.guildId};if(req.query.userId)where.userId=String(req.query.userId);const cases=await ModerationCase.findAll({where,order:[["createdAt","DESC"]],limit:100});res.json({cases});}catch(e){res.status(500).json({error:"Database query failed."})}});
  app.listen(config.dashboard.port,()=>console.log(`Cerberus dashboard listening on port ${config.dashboard.port}`));
}