import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChatInputCommandInteraction, EmbedBuilder, SlashCommandBuilder } from "discord.js";
import { FalloutBuild, falloutBuildsByArchetype, latestFalloutBuilds, searchFalloutBuilds, topFalloutBuilds } from "../services/falloutBuilds";
export const buildCommands=[new SlashCommandBuilder().setName("build").setDescription("Search Fallout 76 builds from FalloutBuilds.com")
 .addSubcommand(s=>s.setName("search").setDescription("Search build names, archetypes, and authors").addStringOption(o=>o.setName("query").setDescription("Search terms").setRequired(true).setMaxLength(100)))
 .addSubcommand(s=>s.setName("archetype").setDescription("Find builds by archetype").addStringOption(o=>o.setName("type").setDescription("e.g. Commando, Heavy Gunner, Rifleman").setRequired(true).setMaxLength(50)))
 .addSubcommand(s=>s.setName("latest").setDescription("Show recently listed Fallout 76 builds"))
 .addSubcommand(s=>s.setName("top").setDescription("Show top-voted builds from the current directory page"))];
function embed(items:FalloutBuild[],title:string){const shown=items.slice(0,10);return new EmbedBuilder().setTitle("☢ "+title).setURL("https://www.falloutbuilds.com/fo76/builds/").setColor(0xf0c419).setDescription(shown.length?shown.map((b,i)=>"**"+(i+1)+". ["+b.title+"]("+b.url+")**\n"+b.archetype+" • "+(b.special||"S.P.E.C.I.A.L. unavailable")+" • "+(b.votes>=0?"+":"")+b.votes+" votes\nBy "+b.author+" • Updated "+b.updated).join("\n\n"):"No matching builds were found.").setFooter({text:"Data: FalloutBuilds.com • Results cached for 10 minutes"}).setTimestamp()}
export async function handleBuildCommand(i:ChatInputCommandInteraction):Promise<void>{await i.deferReply();try{const sub=i.options.getSubcommand();let items:FalloutBuild[]=[],title="Fallout 76 Builds";if(sub==="search"){const q=i.options.getString("query",true);items=await searchFalloutBuilds(q);title='Build Search: "'+q+'"'}else if(sub==="archetype"){const q=i.options.getString("type",true);items=await falloutBuildsByArchetype(q);title=q+" Builds"}else if(sub==="latest"){items=await latestFalloutBuilds();title="Latest Fallout 76 Builds"}else{items=await topFalloutBuilds();title="Top Fallout 76 Builds"}const row=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setLabel("Browse FalloutBuilds.com").setStyle(ButtonStyle.Link).setURL("https://www.falloutbuilds.com/fo76/builds/"));await i.editReply({embeds:[embed(items,title)],components:[row]});}catch(e){console.error("FalloutBuilds search failed:",e);await i.editReply("I couldn't retrieve FalloutBuilds.com right now. Please try again shortly.");}}
