import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChatInputCommandInteraction, ComponentType, EmbedBuilder, SlashCommandBuilder } from "discord.js";
import { NukaListing,NukaPrice,searchNukaMarket,searchNukaPrices } from "../services/nukaTrader";
export const nukaTraderCommands=[
 new SlashCommandBuilder().setName("price").setDescription("Search NukaTrader Fallout 76 item valuations").addSubcommand(s=>s.setName("search").setDescription("Search item prices").addStringOption(o=>o.setName("item").setDescription("Item name").setRequired(true).setMaxLength(100))),
 new SlashCommandBuilder().setName("market").setDescription("Search NukaTrader player trade listings").addSubcommand(s=>s.setName("search").setDescription("Search recent trade listings").addStringOption(o=>o.setName("platform").setDescription("Platform").setRequired(true).addChoices({name:"PC / Steam",value:"pc"},{name:"Xbox",value:"xbox"},{name:"PlayStation",value:"playstation"})).addStringOption(o=>o.setName("item").setDescription("Item or trade search").setRequired(true).setMaxLength(100)))
];
function priceEmbed(x:NukaPrice[],q:string){return new EmbedBuilder().setTitle("☢ NukaTrader Price Search").setURL("https://nukatrader.com/find/").setColor(0xf0c419).setDescription(x.length?x.slice(0,5).map(v=>"**["+v.name+"]("+v.url+")**\nEstimated: **"+v.recommended+"** • Low: "+v.low+" • High: "+v.high+"\nFlux: "+v.flux+" • "+v.type+" / "+v.category).join("\n\n"):"No matching NukaTrader valuation was found for **"+q+"**.").setFooter({text:"NukaTrader estimated valuations • Not a guaranteed sale price • Cached 10 min"}).setTimestamp()}
function marketEmbed(x:NukaListing[],platform:string,q:string,page:number){const size=5,start=page*size,pages=Math.max(1,Math.ceil(x.length/size));return new EmbedBuilder().setTitle("☢ NukaTrader Market • "+platform.toUpperCase()).setURL("https://nukatrader.com/tradingpost/").setColor(0xf0c419).setDescription(x.length?x.slice(start,start+size).map((v,n)=>"**"+(start+n+1)+". ["+v.title+"]("+v.url+")**\n"+v.date+" • "+v.source).join("\n\n"):"No matching recent listings found for **"+q+"**.").setFooter({text:x.length+" result(s) • Page "+(page+1)+"/"+pages+" • Listings sourced via NukaTrader"}).setTimestamp()}
function nav(page:number,pages:number){return new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId("market:prev").setLabel("Previous").setStyle(ButtonStyle.Secondary).setDisabled(page===0),new ButtonBuilder().setCustomId("market:next").setLabel("Next").setStyle(ButtonStyle.Primary).setDisabled(page>=pages-1),new ButtonBuilder().setLabel("NukaTrader").setStyle(ButtonStyle.Link).setURL("https://nukatrader.com/tradingpost/"))}
export async function handleNukaTraderCommand(i:ChatInputCommandInteraction){await i.deferReply();try{if(i.commandName==="price"){const q=i.options.getString("item",true),items=await searchNukaPrices(q);await i.editReply({embeds:[priceEmbed(items,q)]});return}const platform=i.options.getString("platform",true),q=i.options.getString("item",true),items=await searchNukaMarket(platform,q),pages=Math.max(1,Math.ceil(items.length/5));let page=0;const msg=await i.editReply({embeds:[marketEmbed(items,platform,q,page)],components:[nav(page,pages)]});if(pages<=1)return;const col=msg.createMessageComponentCollector({componentType:ComponentType.Button,time:120000,filter:b=>b.user.id===i.user.id&&b.customId.startsWith("market:")});col.on("collect",async b=>{page=b.customId==="market:next"?Math.min(pages-1,page+1):Math.max(0,page-1);await b.update({embeds:[marketEmbed(items,platform,q,page)],components:[nav(page,pages)]})})}catch(e){console.error("NukaTrader command failed:",e);await i.editReply("I couldn't retrieve NukaTrader right now. Please try again shortly.")}}
