-- Cerberus schema for PostgreSQL.
-- Import this into the database configured with dialect: "postgres".

CREATE TABLE IF NOT EXISTS "warnings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "guildId" VARCHAR(32) NOT NULL,
  "userId" VARCHAR(32) NOT NULL,
  "moderatorId" VARCHAR(32) NOT NULL,
  "reason" TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
